const deckDatabase = [
  { cardName: 'FalleN',
    cardDescription: 'Confia no verdadeiro',
    cardAttr1: 90,
    cardAttr2: 90,
    cardAttr3: 90,
    cardImage: 'https://s2.glbimg.com/2NTr8rRdVbXgjXTleSCy2QYB_Z4=/0x0:800x533/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2022/n/T/KFaqzxSS6WV1jBkslWQA/imperial-fallen.jpg',
    cardRare: 'muito rara',
    cardTrunfo: true,
    hasDelete: true,
    className: 'card trunfoBg',

  }, { cardName: 'fer',
    cardDescription: 'Dona Morte',
    cardAttr1: 86,
    cardAttr2: 84,
    cardAttr3: 82,
    cardImage: 'https://theclutch.com.br/wp-content/uploads/2020/11/fer-faixa-mibr.jpg',
    cardRare: 'muito raro',
    cardTrunfo: false,
    hasDelete: true,
    className: 'card muitoRaroBg',

  }, { cardName: 'fnx',
    cardDescription: '6 Mundial, 5 Panamericano, 4 BBB, 3 Banheira do gugu',
    cardAttr1: 82,
    cardAttr2: 80,
    cardAttr3: 90,
    cardImage: 'https://pbs.twimg.com/media/FQJQXTWXoAAeOAL?format=jpg&name=4096x4096',
    cardRare: 'muito raro',
    cardTrunfo: false,
    hasDelete: true,
    className: 'card muitoRaroBg',

  }, { cardName: 'boltz',
    cardDescription: 'A rocha',
    cardAttr1: 83,
    cardAttr2: 85,
    cardAttr3: 80,
    cardImage: 'https://scontent.fplu19-1.fna.fbcdn.net/v/t39.30808-6/278108707_532476185107755_3465685531593787337_n.jpg?_nc_cat=111&ccb=1-6&_nc_sid=09cbfe&_nc_ohc=qxvA_JTYm6YAX-QolBD&_nc_ht=scontent.fplu19-1.fna&oh=00_AT_WjC7kd-eOU3ZYbkikwQneAjmtHZ-WHEL6cezmLdQwEg&oe=62848B62',
    cardRare: 'raro',
    cardTrunfo: false,
    hasDelete: true,
    className: 'card raroBg',

  }, { cardName: 'VINI',
    cardDescription: 'Tubarão martelo',
    cardAttr1: 88,
    cardAttr2: 78,
    cardAttr3: 80,
    cardImage: 'https://theclutch.com.br/wp-content/uploads/2022/05/vini-major.jpg',
    cardRare: 'raro',
    cardTrunfo: false,
    hasDelete: true,
    className: 'card raroBg',
  },
];

export default deckDatabase;
